/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffRegisterRouteImport } from './routes/staff/register'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffLayoutRouteImport } from './routes/staff/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as StaffLayoutIndexRouteImport } from './routes/staff/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as StaffLayoutStockRouteImport } from './routes/staff/_layout/stock'
import { Route as StaffLayoutProfileRouteImport } from './routes/staff/_layout/profile'
import { Route as StaffLayoutGudangRouteImport } from './routes/staff/_layout/gudang'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutProfileRouteImport } from './routes/admin/_layout/profile'
import { Route as StaffLayoutNotifikasiIndexRouteImport } from './routes/staff/_layout/notifikasi/index'
import { Route as StaffLayoutInboundIndexRouteImport } from './routes/staff/_layout/inbound/index'
import { Route as AdminLayoutPusatPersetujuanIndexRouteImport } from './routes/admin/_layout/pusat-persetujuan/index'
import { Route as AdminLayoutPesananPenjualanIndexRouteImport } from './routes/admin/_layout/pesanan-penjualan/index'
import { Route as AdminLayoutPesananPembelianIndexRouteImport } from './routes/admin/_layout/pesanan-pembelian/index'
import { Route as AdminLayoutPelacakanKirimanIndexRouteImport } from './routes/admin/_layout/pelacakan-kiriman/index'
import { Route as AdminLayoutNotifikasiIndexRouteImport } from './routes/admin/_layout/notifikasi/index'
import { Route as AdminLayoutManajemenPenggunaIndexRouteImport } from './routes/admin/_layout/manajemen-pengguna/index'
import { Route as AdminLayoutManajemenGudangIndexRouteImport } from './routes/admin/_layout/manajemen-gudang/index'
import { Route as AdminLayoutKontrolPenerimaanIndexRouteImport } from './routes/admin/_layout/kontrol-penerimaan/index'
import { Route as AdminLayoutKatalogProdukIndexRouteImport } from './routes/admin/_layout/katalog-produk/index'
import { Route as AdminLayoutDirektoriSupplierIndexRouteImport } from './routes/admin/_layout/direktori-supplier/index'
import { Route as AdminLayoutAnalitikLaporanIndexRouteImport } from './routes/admin/_layout/analitik-laporan/index'
import { Route as StaffLayoutInboundPoIdRouteImport } from './routes/staff/_layout/inbound/$poId'
import { Route as AdminLayoutPesananPenjualanCreateRouteImport } from './routes/admin/_layout/pesanan-penjualan/create'
import { Route as AdminLayoutPesananPembelianCreateRouteImport } from './routes/admin/_layout/pesanan-pembelian/create'
import { Route as AdminLayoutKatalogProdukProductIdRouteImport } from './routes/admin/_layout/katalog-produk/$productId'
import { Route as AdminLayoutPesananPenjualanSoIdIndexRouteImport } from './routes/admin/_layout/pesanan-penjualan/$soId.index'
import { Route as AdminLayoutPesananPembelianPoIdIndexRouteImport } from './routes/admin/_layout/pesanan-pembelian/$poId.index'
import { Route as AdminLayoutPesananPenjualanSoIdEditRouteImport } from './routes/admin/_layout/pesanan-penjualan/$soId.edit'
import { Route as AdminLayoutPesananPembelianPoIdEditRouteImport } from './routes/admin/_layout/pesanan-pembelian/$poId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRegisterRoute = StaffRegisterRouteImport.update({
  id: '/staff/register',
  path: '/staff/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLayoutRoute = StaffLayoutRouteImport.update({
  id: '/staff/_layout',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLayoutIndexRoute = StaffLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const StaffLayoutStockRoute = StaffLayoutStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const StaffLayoutProfileRoute = StaffLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const StaffLayoutGudangRoute = StaffLayoutGudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProfileRoute = AdminLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const StaffLayoutNotifikasiIndexRoute =
  StaffLayoutNotifikasiIndexRouteImport.update({
    id: '/notifikasi/',
    path: '/notifikasi/',
    getParentRoute: () => StaffLayoutRoute,
  } as any)
const StaffLayoutInboundIndexRoute = StaffLayoutInboundIndexRouteImport.update({
  id: '/inbound/',
  path: '/inbound/',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const AdminLayoutPusatPersetujuanIndexRoute =
  AdminLayoutPusatPersetujuanIndexRouteImport.update({
    id: '/pusat-persetujuan/',
    path: '/pusat-persetujuan/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPesananPenjualanIndexRoute =
  AdminLayoutPesananPenjualanIndexRouteImport.update({
    id: '/pesanan-penjualan/',
    path: '/pesanan-penjualan/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPesananPembelianIndexRoute =
  AdminLayoutPesananPembelianIndexRouteImport.update({
    id: '/pesanan-pembelian/',
    path: '/pesanan-pembelian/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPelacakanKirimanIndexRoute =
  AdminLayoutPelacakanKirimanIndexRouteImport.update({
    id: '/pelacakan-kiriman/',
    path: '/pelacakan-kiriman/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutNotifikasiIndexRoute =
  AdminLayoutNotifikasiIndexRouteImport.update({
    id: '/notifikasi/',
    path: '/notifikasi/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutManajemenPenggunaIndexRoute =
  AdminLayoutManajemenPenggunaIndexRouteImport.update({
    id: '/manajemen-pengguna/',
    path: '/manajemen-pengguna/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutManajemenGudangIndexRoute =
  AdminLayoutManajemenGudangIndexRouteImport.update({
    id: '/manajemen-gudang/',
    path: '/manajemen-gudang/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutKontrolPenerimaanIndexRoute =
  AdminLayoutKontrolPenerimaanIndexRouteImport.update({
    id: '/kontrol-penerimaan/',
    path: '/kontrol-penerimaan/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutKatalogProdukIndexRoute =
  AdminLayoutKatalogProdukIndexRouteImport.update({
    id: '/katalog-produk/',
    path: '/katalog-produk/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDirektoriSupplierIndexRoute =
  AdminLayoutDirektoriSupplierIndexRouteImport.update({
    id: '/direktori-supplier/',
    path: '/direktori-supplier/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAnalitikLaporanIndexRoute =
  AdminLayoutAnalitikLaporanIndexRouteImport.update({
    id: '/analitik-laporan/',
    path: '/analitik-laporan/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const StaffLayoutInboundPoIdRoute = StaffLayoutInboundPoIdRouteImport.update({
  id: '/inbound/$poId',
  path: '/inbound/$poId',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const AdminLayoutPesananPenjualanCreateRoute =
  AdminLayoutPesananPenjualanCreateRouteImport.update({
    id: '/pesanan-penjualan/create',
    path: '/pesanan-penjualan/create',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPesananPembelianCreateRoute =
  AdminLayoutPesananPembelianCreateRouteImport.update({
    id: '/pesanan-pembelian/create',
    path: '/pesanan-pembelian/create',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutKatalogProdukProductIdRoute =
  AdminLayoutKatalogProdukProductIdRouteImport.update({
    id: '/katalog-produk/$productId',
    path: '/katalog-produk/$productId',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPesananPenjualanSoIdIndexRoute =
  AdminLayoutPesananPenjualanSoIdIndexRouteImport.update({
    id: '/pesanan-penjualan/$soId/',
    path: '/pesanan-penjualan/$soId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPesananPembelianPoIdIndexRoute =
  AdminLayoutPesananPembelianPoIdIndexRouteImport.update({
    id: '/pesanan-pembelian/$poId/',
    path: '/pesanan-pembelian/$poId/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPesananPenjualanSoIdEditRoute =
  AdminLayoutPesananPenjualanSoIdEditRouteImport.update({
    id: '/pesanan-penjualan/$soId/edit',
    path: '/pesanan-penjualan/$soId/edit',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPesananPembelianPoIdEditRoute =
  AdminLayoutPesananPembelianPoIdEditRouteImport.update({
    id: '/pesanan-pembelian/$poId/edit',
    path: '/pesanan-pembelian/$poId/edit',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/staff': typeof StaffLayoutRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/staff/register': typeof StaffRegisterRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/staff/gudang': typeof StaffLayoutGudangRoute
  '/staff/profile': typeof StaffLayoutProfileRoute
  '/staff/stock': typeof StaffLayoutStockRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/staff/': typeof StaffLayoutIndexRoute
  '/admin/katalog-produk/$productId': typeof AdminLayoutKatalogProdukProductIdRoute
  '/admin/pesanan-pembelian/create': typeof AdminLayoutPesananPembelianCreateRoute
  '/admin/pesanan-penjualan/create': typeof AdminLayoutPesananPenjualanCreateRoute
  '/staff/inbound/$poId': typeof StaffLayoutInboundPoIdRoute
  '/admin/analitik-laporan/': typeof AdminLayoutAnalitikLaporanIndexRoute
  '/admin/direktori-supplier/': typeof AdminLayoutDirektoriSupplierIndexRoute
  '/admin/katalog-produk/': typeof AdminLayoutKatalogProdukIndexRoute
  '/admin/kontrol-penerimaan/': typeof AdminLayoutKontrolPenerimaanIndexRoute
  '/admin/manajemen-gudang/': typeof AdminLayoutManajemenGudangIndexRoute
  '/admin/manajemen-pengguna/': typeof AdminLayoutManajemenPenggunaIndexRoute
  '/admin/notifikasi/': typeof AdminLayoutNotifikasiIndexRoute
  '/admin/pelacakan-kiriman/': typeof AdminLayoutPelacakanKirimanIndexRoute
  '/admin/pesanan-pembelian/': typeof AdminLayoutPesananPembelianIndexRoute
  '/admin/pesanan-penjualan/': typeof AdminLayoutPesananPenjualanIndexRoute
  '/admin/pusat-persetujuan/': typeof AdminLayoutPusatPersetujuanIndexRoute
  '/staff/inbound/': typeof StaffLayoutInboundIndexRoute
  '/staff/notifikasi/': typeof StaffLayoutNotifikasiIndexRoute
  '/admin/pesanan-pembelian/$poId/edit': typeof AdminLayoutPesananPembelianPoIdEditRoute
  '/admin/pesanan-penjualan/$soId/edit': typeof AdminLayoutPesananPenjualanSoIdEditRoute
  '/admin/pesanan-pembelian/$poId/': typeof AdminLayoutPesananPembelianPoIdIndexRoute
  '/admin/pesanan-penjualan/$soId/': typeof AdminLayoutPesananPenjualanSoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/register': typeof StaffRegisterRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/staff/gudang': typeof StaffLayoutGudangRoute
  '/staff/profile': typeof StaffLayoutProfileRoute
  '/staff/stock': typeof StaffLayoutStockRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/staff': typeof StaffLayoutIndexRoute
  '/admin/katalog-produk/$productId': typeof AdminLayoutKatalogProdukProductIdRoute
  '/admin/pesanan-pembelian/create': typeof AdminLayoutPesananPembelianCreateRoute
  '/admin/pesanan-penjualan/create': typeof AdminLayoutPesananPenjualanCreateRoute
  '/staff/inbound/$poId': typeof StaffLayoutInboundPoIdRoute
  '/admin/analitik-laporan': typeof AdminLayoutAnalitikLaporanIndexRoute
  '/admin/direktori-supplier': typeof AdminLayoutDirektoriSupplierIndexRoute
  '/admin/katalog-produk': typeof AdminLayoutKatalogProdukIndexRoute
  '/admin/kontrol-penerimaan': typeof AdminLayoutKontrolPenerimaanIndexRoute
  '/admin/manajemen-gudang': typeof AdminLayoutManajemenGudangIndexRoute
  '/admin/manajemen-pengguna': typeof AdminLayoutManajemenPenggunaIndexRoute
  '/admin/notifikasi': typeof AdminLayoutNotifikasiIndexRoute
  '/admin/pelacakan-kiriman': typeof AdminLayoutPelacakanKirimanIndexRoute
  '/admin/pesanan-pembelian': typeof AdminLayoutPesananPembelianIndexRoute
  '/admin/pesanan-penjualan': typeof AdminLayoutPesananPenjualanIndexRoute
  '/admin/pusat-persetujuan': typeof AdminLayoutPusatPersetujuanIndexRoute
  '/staff/inbound': typeof StaffLayoutInboundIndexRoute
  '/staff/notifikasi': typeof StaffLayoutNotifikasiIndexRoute
  '/admin/pesanan-pembelian/$poId/edit': typeof AdminLayoutPesananPembelianPoIdEditRoute
  '/admin/pesanan-penjualan/$soId/edit': typeof AdminLayoutPesananPenjualanSoIdEditRoute
  '/admin/pesanan-pembelian/$poId': typeof AdminLayoutPesananPembelianPoIdIndexRoute
  '/admin/pesanan-penjualan/$soId': typeof AdminLayoutPesananPenjualanSoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/staff/_layout': typeof StaffLayoutRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/staff/register': typeof StaffRegisterRoute
  '/admin/_layout/profile': typeof AdminLayoutProfileRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/staff/_layout/gudang': typeof StaffLayoutGudangRoute
  '/staff/_layout/profile': typeof StaffLayoutProfileRoute
  '/staff/_layout/stock': typeof StaffLayoutStockRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/staff/_layout/': typeof StaffLayoutIndexRoute
  '/admin/_layout/katalog-produk/$productId': typeof AdminLayoutKatalogProdukProductIdRoute
  '/admin/_layout/pesanan-pembelian/create': typeof AdminLayoutPesananPembelianCreateRoute
  '/admin/_layout/pesanan-penjualan/create': typeof AdminLayoutPesananPenjualanCreateRoute
  '/staff/_layout/inbound/$poId': typeof StaffLayoutInboundPoIdRoute
  '/admin/_layout/analitik-laporan/': typeof AdminLayoutAnalitikLaporanIndexRoute
  '/admin/_layout/direktori-supplier/': typeof AdminLayoutDirektoriSupplierIndexRoute
  '/admin/_layout/katalog-produk/': typeof AdminLayoutKatalogProdukIndexRoute
  '/admin/_layout/kontrol-penerimaan/': typeof AdminLayoutKontrolPenerimaanIndexRoute
  '/admin/_layout/manajemen-gudang/': typeof AdminLayoutManajemenGudangIndexRoute
  '/admin/_layout/manajemen-pengguna/': typeof AdminLayoutManajemenPenggunaIndexRoute
  '/admin/_layout/notifikasi/': typeof AdminLayoutNotifikasiIndexRoute
  '/admin/_layout/pelacakan-kiriman/': typeof AdminLayoutPelacakanKirimanIndexRoute
  '/admin/_layout/pesanan-pembelian/': typeof AdminLayoutPesananPembelianIndexRoute
  '/admin/_layout/pesanan-penjualan/': typeof AdminLayoutPesananPenjualanIndexRoute
  '/admin/_layout/pusat-persetujuan/': typeof AdminLayoutPusatPersetujuanIndexRoute
  '/staff/_layout/inbound/': typeof StaffLayoutInboundIndexRoute
  '/staff/_layout/notifikasi/': typeof StaffLayoutNotifikasiIndexRoute
  '/admin/_layout/pesanan-pembelian/$poId/edit': typeof AdminLayoutPesananPembelianPoIdEditRoute
  '/admin/_layout/pesanan-penjualan/$soId/edit': typeof AdminLayoutPesananPenjualanSoIdEditRoute
  '/admin/_layout/pesanan-pembelian/$poId/': typeof AdminLayoutPesananPembelianPoIdIndexRoute
  '/admin/_layout/pesanan-penjualan/$soId/': typeof AdminLayoutPesananPenjualanSoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/staff'
    | '/staff/login'
    | '/staff/register'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/staff/gudang'
    | '/staff/profile'
    | '/staff/stock'
    | '/admin/'
    | '/staff/'
    | '/admin/katalog-produk/$productId'
    | '/admin/pesanan-pembelian/create'
    | '/admin/pesanan-penjualan/create'
    | '/staff/inbound/$poId'
    | '/admin/analitik-laporan/'
    | '/admin/direktori-supplier/'
    | '/admin/katalog-produk/'
    | '/admin/kontrol-penerimaan/'
    | '/admin/manajemen-gudang/'
    | '/admin/manajemen-pengguna/'
    | '/admin/notifikasi/'
    | '/admin/pelacakan-kiriman/'
    | '/admin/pesanan-pembelian/'
    | '/admin/pesanan-penjualan/'
    | '/admin/pusat-persetujuan/'
    | '/staff/inbound/'
    | '/staff/notifikasi/'
    | '/admin/pesanan-pembelian/$poId/edit'
    | '/admin/pesanan-penjualan/$soId/edit'
    | '/admin/pesanan-pembelian/$poId/'
    | '/admin/pesanan-penjualan/$soId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/staff/login'
    | '/staff/register'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/staff/gudang'
    | '/staff/profile'
    | '/staff/stock'
    | '/admin'
    | '/staff'
    | '/admin/katalog-produk/$productId'
    | '/admin/pesanan-pembelian/create'
    | '/admin/pesanan-penjualan/create'
    | '/staff/inbound/$poId'
    | '/admin/analitik-laporan'
    | '/admin/direktori-supplier'
    | '/admin/katalog-produk'
    | '/admin/kontrol-penerimaan'
    | '/admin/manajemen-gudang'
    | '/admin/manajemen-pengguna'
    | '/admin/notifikasi'
    | '/admin/pelacakan-kiriman'
    | '/admin/pesanan-pembelian'
    | '/admin/pesanan-penjualan'
    | '/admin/pusat-persetujuan'
    | '/staff/inbound'
    | '/staff/notifikasi'
    | '/admin/pesanan-pembelian/$poId/edit'
    | '/admin/pesanan-penjualan/$soId/edit'
    | '/admin/pesanan-pembelian/$poId'
    | '/admin/pesanan-penjualan/$soId'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/staff/_layout'
    | '/staff/login'
    | '/staff/register'
    | '/admin/_layout/profile'
    | '/admin/_layout/settings'
    | '/admin/_layout/users'
    | '/staff/_layout/gudang'
    | '/staff/_layout/profile'
    | '/staff/_layout/stock'
    | '/admin/_layout/'
    | '/staff/_layout/'
    | '/admin/_layout/katalog-produk/$productId'
    | '/admin/_layout/pesanan-pembelian/create'
    | '/admin/_layout/pesanan-penjualan/create'
    | '/staff/_layout/inbound/$poId'
    | '/admin/_layout/analitik-laporan/'
    | '/admin/_layout/direktori-supplier/'
    | '/admin/_layout/katalog-produk/'
    | '/admin/_layout/kontrol-penerimaan/'
    | '/admin/_layout/manajemen-gudang/'
    | '/admin/_layout/manajemen-pengguna/'
    | '/admin/_layout/notifikasi/'
    | '/admin/_layout/pelacakan-kiriman/'
    | '/admin/_layout/pesanan-pembelian/'
    | '/admin/_layout/pesanan-penjualan/'
    | '/admin/_layout/pusat-persetujuan/'
    | '/staff/_layout/inbound/'
    | '/staff/_layout/notifikasi/'
    | '/admin/_layout/pesanan-pembelian/$poId/edit'
    | '/admin/_layout/pesanan-penjualan/$soId/edit'
    | '/admin/_layout/pesanan-pembelian/$poId/'
    | '/admin/_layout/pesanan-penjualan/$soId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  StaffLayoutRoute: typeof StaffLayoutRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  StaffRegisterRoute: typeof StaffRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/register': {
      id: '/staff/register'
      path: '/staff/register'
      fullPath: '/staff/register'
      preLoaderRoute: typeof StaffRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_layout': {
      id: '/staff/_layout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_layout/': {
      id: '/staff/_layout/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffLayoutIndexRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/staff/_layout/stock': {
      id: '/staff/_layout/stock'
      path: '/stock'
      fullPath: '/staff/stock'
      preLoaderRoute: typeof StaffLayoutStockRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/staff/_layout/profile': {
      id: '/staff/_layout/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffLayoutProfileRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/staff/_layout/gudang': {
      id: '/staff/_layout/gudang'
      path: '/gudang'
      fullPath: '/staff/gudang'
      preLoaderRoute: typeof StaffLayoutGudangRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/profile': {
      id: '/admin/_layout/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminLayoutProfileRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/staff/_layout/notifikasi/': {
      id: '/staff/_layout/notifikasi/'
      path: '/notifikasi'
      fullPath: '/staff/notifikasi/'
      preLoaderRoute: typeof StaffLayoutNotifikasiIndexRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/staff/_layout/inbound/': {
      id: '/staff/_layout/inbound/'
      path: '/inbound'
      fullPath: '/staff/inbound/'
      preLoaderRoute: typeof StaffLayoutInboundIndexRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/admin/_layout/pusat-persetujuan/': {
      id: '/admin/_layout/pusat-persetujuan/'
      path: '/pusat-persetujuan'
      fullPath: '/admin/pusat-persetujuan/'
      preLoaderRoute: typeof AdminLayoutPusatPersetujuanIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pesanan-penjualan/': {
      id: '/admin/_layout/pesanan-penjualan/'
      path: '/pesanan-penjualan'
      fullPath: '/admin/pesanan-penjualan/'
      preLoaderRoute: typeof AdminLayoutPesananPenjualanIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pesanan-pembelian/': {
      id: '/admin/_layout/pesanan-pembelian/'
      path: '/pesanan-pembelian'
      fullPath: '/admin/pesanan-pembelian/'
      preLoaderRoute: typeof AdminLayoutPesananPembelianIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pelacakan-kiriman/': {
      id: '/admin/_layout/pelacakan-kiriman/'
      path: '/pelacakan-kiriman'
      fullPath: '/admin/pelacakan-kiriman/'
      preLoaderRoute: typeof AdminLayoutPelacakanKirimanIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/notifikasi/': {
      id: '/admin/_layout/notifikasi/'
      path: '/notifikasi'
      fullPath: '/admin/notifikasi/'
      preLoaderRoute: typeof AdminLayoutNotifikasiIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/manajemen-pengguna/': {
      id: '/admin/_layout/manajemen-pengguna/'
      path: '/manajemen-pengguna'
      fullPath: '/admin/manajemen-pengguna/'
      preLoaderRoute: typeof AdminLayoutManajemenPenggunaIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/manajemen-gudang/': {
      id: '/admin/_layout/manajemen-gudang/'
      path: '/manajemen-gudang'
      fullPath: '/admin/manajemen-gudang/'
      preLoaderRoute: typeof AdminLayoutManajemenGudangIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/kontrol-penerimaan/': {
      id: '/admin/_layout/kontrol-penerimaan/'
      path: '/kontrol-penerimaan'
      fullPath: '/admin/kontrol-penerimaan/'
      preLoaderRoute: typeof AdminLayoutKontrolPenerimaanIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/katalog-produk/': {
      id: '/admin/_layout/katalog-produk/'
      path: '/katalog-produk'
      fullPath: '/admin/katalog-produk/'
      preLoaderRoute: typeof AdminLayoutKatalogProdukIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/direktori-supplier/': {
      id: '/admin/_layout/direktori-supplier/'
      path: '/direktori-supplier'
      fullPath: '/admin/direktori-supplier/'
      preLoaderRoute: typeof AdminLayoutDirektoriSupplierIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/analitik-laporan/': {
      id: '/admin/_layout/analitik-laporan/'
      path: '/analitik-laporan'
      fullPath: '/admin/analitik-laporan/'
      preLoaderRoute: typeof AdminLayoutAnalitikLaporanIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/staff/_layout/inbound/$poId': {
      id: '/staff/_layout/inbound/$poId'
      path: '/inbound/$poId'
      fullPath: '/staff/inbound/$poId'
      preLoaderRoute: typeof StaffLayoutInboundPoIdRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/admin/_layout/pesanan-penjualan/create': {
      id: '/admin/_layout/pesanan-penjualan/create'
      path: '/pesanan-penjualan/create'
      fullPath: '/admin/pesanan-penjualan/create'
      preLoaderRoute: typeof AdminLayoutPesananPenjualanCreateRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pesanan-pembelian/create': {
      id: '/admin/_layout/pesanan-pembelian/create'
      path: '/pesanan-pembelian/create'
      fullPath: '/admin/pesanan-pembelian/create'
      preLoaderRoute: typeof AdminLayoutPesananPembelianCreateRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/katalog-produk/$productId': {
      id: '/admin/_layout/katalog-produk/$productId'
      path: '/katalog-produk/$productId'
      fullPath: '/admin/katalog-produk/$productId'
      preLoaderRoute: typeof AdminLayoutKatalogProdukProductIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pesanan-penjualan/$soId/': {
      id: '/admin/_layout/pesanan-penjualan/$soId/'
      path: '/pesanan-penjualan/$soId'
      fullPath: '/admin/pesanan-penjualan/$soId/'
      preLoaderRoute: typeof AdminLayoutPesananPenjualanSoIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pesanan-pembelian/$poId/': {
      id: '/admin/_layout/pesanan-pembelian/$poId/'
      path: '/pesanan-pembelian/$poId'
      fullPath: '/admin/pesanan-pembelian/$poId/'
      preLoaderRoute: typeof AdminLayoutPesananPembelianPoIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pesanan-penjualan/$soId/edit': {
      id: '/admin/_layout/pesanan-penjualan/$soId/edit'
      path: '/pesanan-penjualan/$soId/edit'
      fullPath: '/admin/pesanan-penjualan/$soId/edit'
      preLoaderRoute: typeof AdminLayoutPesananPenjualanSoIdEditRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pesanan-pembelian/$poId/edit': {
      id: '/admin/_layout/pesanan-pembelian/$poId/edit'
      path: '/pesanan-pembelian/$poId/edit'
      fullPath: '/admin/pesanan-pembelian/$poId/edit'
      preLoaderRoute: typeof AdminLayoutPesananPembelianPoIdEditRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutProfileRoute: typeof AdminLayoutProfileRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutKatalogProdukProductIdRoute: typeof AdminLayoutKatalogProdukProductIdRoute
  AdminLayoutPesananPembelianCreateRoute: typeof AdminLayoutPesananPembelianCreateRoute
  AdminLayoutPesananPenjualanCreateRoute: typeof AdminLayoutPesananPenjualanCreateRoute
  AdminLayoutAnalitikLaporanIndexRoute: typeof AdminLayoutAnalitikLaporanIndexRoute
  AdminLayoutDirektoriSupplierIndexRoute: typeof AdminLayoutDirektoriSupplierIndexRoute
  AdminLayoutKatalogProdukIndexRoute: typeof AdminLayoutKatalogProdukIndexRoute
  AdminLayoutKontrolPenerimaanIndexRoute: typeof AdminLayoutKontrolPenerimaanIndexRoute
  AdminLayoutManajemenGudangIndexRoute: typeof AdminLayoutManajemenGudangIndexRoute
  AdminLayoutManajemenPenggunaIndexRoute: typeof AdminLayoutManajemenPenggunaIndexRoute
  AdminLayoutNotifikasiIndexRoute: typeof AdminLayoutNotifikasiIndexRoute
  AdminLayoutPelacakanKirimanIndexRoute: typeof AdminLayoutPelacakanKirimanIndexRoute
  AdminLayoutPesananPembelianIndexRoute: typeof AdminLayoutPesananPembelianIndexRoute
  AdminLayoutPesananPenjualanIndexRoute: typeof AdminLayoutPesananPenjualanIndexRoute
  AdminLayoutPusatPersetujuanIndexRoute: typeof AdminLayoutPusatPersetujuanIndexRoute
  AdminLayoutPesananPembelianPoIdEditRoute: typeof AdminLayoutPesananPembelianPoIdEditRoute
  AdminLayoutPesananPenjualanSoIdEditRoute: typeof AdminLayoutPesananPenjualanSoIdEditRoute
  AdminLayoutPesananPembelianPoIdIndexRoute: typeof AdminLayoutPesananPembelianPoIdIndexRoute
  AdminLayoutPesananPenjualanSoIdIndexRoute: typeof AdminLayoutPesananPenjualanSoIdIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutProfileRoute: AdminLayoutProfileRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutKatalogProdukProductIdRoute:
    AdminLayoutKatalogProdukProductIdRoute,
  AdminLayoutPesananPembelianCreateRoute:
    AdminLayoutPesananPembelianCreateRoute,
  AdminLayoutPesananPenjualanCreateRoute:
    AdminLayoutPesananPenjualanCreateRoute,
  AdminLayoutAnalitikLaporanIndexRoute: AdminLayoutAnalitikLaporanIndexRoute,
  AdminLayoutDirektoriSupplierIndexRoute:
    AdminLayoutDirektoriSupplierIndexRoute,
  AdminLayoutKatalogProdukIndexRoute: AdminLayoutKatalogProdukIndexRoute,
  AdminLayoutKontrolPenerimaanIndexRoute:
    AdminLayoutKontrolPenerimaanIndexRoute,
  AdminLayoutManajemenGudangIndexRoute: AdminLayoutManajemenGudangIndexRoute,
  AdminLayoutManajemenPenggunaIndexRoute:
    AdminLayoutManajemenPenggunaIndexRoute,
  AdminLayoutNotifikasiIndexRoute: AdminLayoutNotifikasiIndexRoute,
  AdminLayoutPelacakanKirimanIndexRoute: AdminLayoutPelacakanKirimanIndexRoute,
  AdminLayoutPesananPembelianIndexRoute: AdminLayoutPesananPembelianIndexRoute,
  AdminLayoutPesananPenjualanIndexRoute: AdminLayoutPesananPenjualanIndexRoute,
  AdminLayoutPusatPersetujuanIndexRoute: AdminLayoutPusatPersetujuanIndexRoute,
  AdminLayoutPesananPembelianPoIdEditRoute:
    AdminLayoutPesananPembelianPoIdEditRoute,
  AdminLayoutPesananPenjualanSoIdEditRoute:
    AdminLayoutPesananPenjualanSoIdEditRoute,
  AdminLayoutPesananPembelianPoIdIndexRoute:
    AdminLayoutPesananPembelianPoIdIndexRoute,
  AdminLayoutPesananPenjualanSoIdIndexRoute:
    AdminLayoutPesananPenjualanSoIdIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface StaffLayoutRouteChildren {
  StaffLayoutGudangRoute: typeof StaffLayoutGudangRoute
  StaffLayoutProfileRoute: typeof StaffLayoutProfileRoute
  StaffLayoutStockRoute: typeof StaffLayoutStockRoute
  StaffLayoutIndexRoute: typeof StaffLayoutIndexRoute
  StaffLayoutInboundPoIdRoute: typeof StaffLayoutInboundPoIdRoute
  StaffLayoutInboundIndexRoute: typeof StaffLayoutInboundIndexRoute
  StaffLayoutNotifikasiIndexRoute: typeof StaffLayoutNotifikasiIndexRoute
}

const StaffLayoutRouteChildren: StaffLayoutRouteChildren = {
  StaffLayoutGudangRoute: StaffLayoutGudangRoute,
  StaffLayoutProfileRoute: StaffLayoutProfileRoute,
  StaffLayoutStockRoute: StaffLayoutStockRoute,
  StaffLayoutIndexRoute: StaffLayoutIndexRoute,
  StaffLayoutInboundPoIdRoute: StaffLayoutInboundPoIdRoute,
  StaffLayoutInboundIndexRoute: StaffLayoutInboundIndexRoute,
  StaffLayoutNotifikasiIndexRoute: StaffLayoutNotifikasiIndexRoute,
}

const StaffLayoutRouteWithChildren = StaffLayoutRoute._addFileChildren(
  StaffLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  StaffLayoutRoute: StaffLayoutRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  StaffRegisterRoute: StaffRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
