/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffRegisterRouteImport } from './routes/staff/register'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffLayoutRouteImport } from './routes/staff/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as StaffLayoutIndexRouteImport } from './routes/staff/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as StaffLayoutStockRouteImport } from './routes/staff/_layout/stock'
import { Route as StaffLayoutProfileRouteImport } from './routes/staff/_layout/profile'
import { Route as StaffLayoutGudangRouteImport } from './routes/staff/_layout/gudang'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutProfileRouteImport } from './routes/admin/_layout/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRegisterRoute = StaffRegisterRouteImport.update({
  id: '/staff/register',
  path: '/staff/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLayoutRoute = StaffLayoutRouteImport.update({
  id: '/staff/_layout',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLayoutIndexRoute = StaffLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const StaffLayoutStockRoute = StaffLayoutStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const StaffLayoutProfileRoute = StaffLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const StaffLayoutGudangRoute = StaffLayoutGudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => StaffLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProfileRoute = AdminLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/staff': typeof StaffLayoutRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/staff/register': typeof StaffRegisterRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/staff/gudang': typeof StaffLayoutGudangRoute
  '/staff/profile': typeof StaffLayoutProfileRoute
  '/staff/stock': typeof StaffLayoutStockRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/staff/': typeof StaffLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/register': typeof StaffRegisterRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/staff/gudang': typeof StaffLayoutGudangRoute
  '/staff/profile': typeof StaffLayoutProfileRoute
  '/staff/stock': typeof StaffLayoutStockRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/staff': typeof StaffLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/staff/_layout': typeof StaffLayoutRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/staff/register': typeof StaffRegisterRoute
  '/admin/_layout/profile': typeof AdminLayoutProfileRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/staff/_layout/gudang': typeof StaffLayoutGudangRoute
  '/staff/_layout/profile': typeof StaffLayoutProfileRoute
  '/staff/_layout/stock': typeof StaffLayoutStockRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/staff/_layout/': typeof StaffLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/staff'
    | '/staff/login'
    | '/staff/register'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/staff/gudang'
    | '/staff/profile'
    | '/staff/stock'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/staff/login'
    | '/staff/register'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/staff/gudang'
    | '/staff/profile'
    | '/staff/stock'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/staff/_layout'
    | '/staff/login'
    | '/staff/register'
    | '/admin/_layout/profile'
    | '/admin/_layout/settings'
    | '/admin/_layout/users'
    | '/staff/_layout/gudang'
    | '/staff/_layout/profile'
    | '/staff/_layout/stock'
    | '/admin/_layout/'
    | '/staff/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  StaffLayoutRoute: typeof StaffLayoutRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  StaffRegisterRoute: typeof StaffRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/register': {
      id: '/staff/register'
      path: '/staff/register'
      fullPath: '/staff/register'
      preLoaderRoute: typeof StaffRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_layout': {
      id: '/staff/_layout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/_layout/': {
      id: '/staff/_layout/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffLayoutIndexRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/staff/_layout/stock': {
      id: '/staff/_layout/stock'
      path: '/stock'
      fullPath: '/staff/stock'
      preLoaderRoute: typeof StaffLayoutStockRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/staff/_layout/profile': {
      id: '/staff/_layout/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffLayoutProfileRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/staff/_layout/gudang': {
      id: '/staff/_layout/gudang'
      path: '/gudang'
      fullPath: '/staff/gudang'
      preLoaderRoute: typeof StaffLayoutGudangRouteImport
      parentRoute: typeof StaffLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/profile': {
      id: '/admin/_layout/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminLayoutProfileRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutProfileRoute: typeof AdminLayoutProfileRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutProfileRoute: AdminLayoutProfileRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface StaffLayoutRouteChildren {
  StaffLayoutGudangRoute: typeof StaffLayoutGudangRoute
  StaffLayoutProfileRoute: typeof StaffLayoutProfileRoute
  StaffLayoutStockRoute: typeof StaffLayoutStockRoute
  StaffLayoutIndexRoute: typeof StaffLayoutIndexRoute
}

const StaffLayoutRouteChildren: StaffLayoutRouteChildren = {
  StaffLayoutGudangRoute: StaffLayoutGudangRoute,
  StaffLayoutProfileRoute: StaffLayoutProfileRoute,
  StaffLayoutStockRoute: StaffLayoutStockRoute,
  StaffLayoutIndexRoute: StaffLayoutIndexRoute,
}

const StaffLayoutRouteWithChildren = StaffLayoutRoute._addFileChildren(
  StaffLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  StaffLayoutRoute: StaffLayoutRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  StaffRegisterRoute: StaffRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
